function(rkg_set_target_defaults target)
  target_compile_features(${target} PUBLIC cxx_std_20)
  target_compile_definitions(${target} PRIVATE $<$<CONFIG:Debug>:RKG_DEBUG=1>)
  if(MSVC)
    target_compile_options(${target} PRIVATE /W4 /permissive-)
  else()
    target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
  endif()
endfunction()

function(rkg_add_library target)
  add_library(${target} ${ARGN})
  rkg_set_target_defaults(${target})
endfunction()

function(rkg_add_executable target)
  add_executable(${target} ${ARGN})
  rkg_set_target_defaults(${target})
endfunction()
