project:
  name: demo_game
  renderer: vulkan
  plugins:
    - script_lua
    - script_js
    - debug_ui_imgui
  initial_level: content/levels/demo_level.yaml
  input_map: config/input.yaml
  dev_mode: true
